### PR TITLE
Pass "-hide-all-packages" to ghc in initDynFlag functions

### PR DESCRIPTION
**Pull request by lspitzner**
This is untested, but contains the change that according to standalone-testing of the raw GHC API works.

Note that exactprint also exposes `withDynFlags` which also internally uses `setSessionDynFlags`. This function was _not_ changed, as I don't know what it's purpose is.

### CODE REVIEW

**Comment by alanz** [comment]
I suspect we should make this subject to a flag passed in, there are cases where people may want the files to be parsed.

**Comment by lspitzner** [comment]
Just a Bool, passed to the two (or three) functions?

**Comment by alanz** [comment]
yes. Unless you want to avoid Boolean blindness and make a type.

**Comment by lspitzner** [comment]
you are right, when the semantic can be seen as "ignore package environment files" boolean blindness is likely.

`data HideAllPackagesFlag = ReadPackageEnvFile | IgnorePackageEnvFile` added to `Language.Haskell.GHC.ExactPrint.Types` ? Or something else?

**Comment by alanz** [comment]
That sounds fine

**Comment by lspitzner** [comment]
This affects more functions in the ghc-exactprint API. Have to take a step back and ask: Are package environments ever relevant for module parsing? And should we not strive to provide a proper interface, i.e. to allow to pass a list of packages, instead of doing any side-effecty stuff, if at all?

At this point it seems most sensible to merge this as-is, and wait for anyone to complain. Really that the GHC API is `CWD`-sensitive is a bug, and I see no benefit in supporting the same for ghc-exactprint.

**Comment by alanz** [comment]
@lspitzner that makes sense.

And a thought struck me, does GHC work from the location of the file being parsed, or from the process directory.  In the latter case, setting the directory to `/tmp` before parsing might be an option.

**Comment by lspitzner** [comment]
I am mildly certain it is the latter case, because `setSessionDynFlags` does not know about any input paths. Setting CWD for the current process might work, but it is just such a nasty hack. When exposing an API, the caller could always concurrently set `CWD` to something else. Global variables are just to be avoided. And I bet the cabal devs would quickly find a reason for putting a ghc.environment file into `/tmp` or something.

**Pull request merged**
