### PR TITLE
No identity fail

### PR DESCRIPTION
**Pull request by phadej**

### CODE REVIEW

**Comment by phadej** [comment]
This includes #55 change.
Also solves #66, in the way `haskell-ci` has support for (obsoletes #70)

**Comment by phadej** [comment]
I removed the OSX job adding commit from this branch into #74 as it indeed fails.

**Comment by alanz** [comment]
I guess I should not say "PR's welcome" and then not deal with them.

Will merge after checking the impact on HaRe etc.

**Comment by phadej** [comment]
Thanks @alanz

**Comment by alanz** [comment]
I am waiting for travis to pass then will upload to hackage

**Pull request merged**
